version: "3.5"

services: 
  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=services-pl
      - MYSQL_USER=${DATASOURCE_USERNAME}
      - MYSQL_PASSWORD=${DATASOURCE_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --max-allowed-packet=1024M
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  pl:
    image: benjaminbini/services-pl
    build : .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - WAIT_HOSTS=mysql:3306
    depends_on:
      - mysql