package com.sully.covid.util;

import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.Map;

@Service
public class ListUtils {
    public Map<String, String> getDepartements() {
        Map<String, String> map = new HashMap<>();
        map.put("1", "01 - Ain");
        map.put("2", "02 - Aisne");
        map.put("3", "03 - Allier");
        map.put("4", "04 - Alpes-de-Haute-Provence");
        map.put("5", "05 - Hautes-Alpes");
        map.put("6", "06 - Alpes-Maritimes");
        map.put("7", "07 - Ardèche");
        map.put("8", "08 - Ardennes");
        map.put("9", "09 - Ariège");
        map.put("10", "10 - Aube");
        map.put("11", "11 - Aude");
        map.put("12", "12 - Aveyron");
        map.put("13", "13 - Bouches-du-Rhône");
        map.put("14", "14 - Calvados");
        map.put("15", "15 - Cantal");
        map.put("16", "16 - Charente");
        map.put("17", "17 - Charente-Maritime");
        map.put("18", "18 - Cher");
        map.put("19", "19 - Corrèze");
        map.put("2A", "2A - Corse-du-Sud");
        map.put("2B", "2B - Haute-Corse");
        map.put("21", "21 - Côte-d'Or");
        map.put("22", "22 - Côtes d'Armor");
        map.put("23", "23 - Creuse");
        map.put("24", "24 - Dordogne");
        map.put("25", "25 - Doubs");
        map.put("26", "26 - Drôme");
        map.put("27", "27 - Eure");
        map.put("28", "28 - Eure-et-Loir");
        map.put("29", "29 - Finistère");
        map.put("30", "30 - Gard");
        map.put("31", "31 - Haute-Garonne");
        map.put("32", "32 - Gers");
        map.put("33", "33 - Gironde");
        map.put("34", "34 - Hérault");
        map.put("35", "35 - Ille-et-Vilaine");
        map.put("36", "36 - Indre");
        map.put("37", "37 - Indre-et-Loire");
        map.put("38", "38 - Isère");
        map.put("39", "39 - Jura");
        map.put("40", "40 - Landes");
        map.put("41", "41 - Loir-et-Cher");
        map.put("42", "42 - Loire");
        map.put("43", "43 - Haute-Loire");
        map.put("44", "44 - Loire-Atlantique");
        map.put("45", "45 - Loiret");
        map.put("46", "46 - Lot");
        map.put("47", "47 - Lot-et-Garonne");
        map.put("48", "48 - Lozère");
        map.put("49", "49 - Maine-et-Loire");
        map.put("50", "50 - Manche");
        map.put("51", "51 - Marne");
        map.put("52", "52 - Haute-Marne");
        map.put("53", "53 - Mayenne");
        map.put("54", "54 - Meurthe-et-Moselle");
        map.put("55", "55 - Meuse");
        map.put("56", "56 - Morbihan");
        map.put("57", "57 - Moselle");
        map.put("58", "58 - Nièvre");
        map.put("59", "59 - Nord");
        map.put("60", "60 - Oise");
        map.put("61", "61 - Orne");
        map.put("62", "62 - Pas-de-Calais");
        map.put("63", "63 - Puy-de-Dôme");
        map.put("64", "64 - Pyrénées-Atlantiques");
        map.put("65", "65 - Hautes-Pyrénées");
        map.put("66", "66 - Pyrénées-Orientales");
        map.put("67", "67 - Bas-Rhin");
        map.put("68", "68 - Haut-Rhin");
        map.put("69", "69 - Rhône");
        map.put("70", "70 - Haute-Saône");
        map.put("71", "71 - Saône-et-Loire");
        map.put("72", "72 - Sarthe");
        map.put("73", "73 - Savoie");
        map.put("74", "74 - Haute-Savoie");
        map.put("75", "75 - Paris");
        map.put("76", "76 - Seine-Maritime");
        map.put("77", "77 - Seine-et-Marne");
        map.put("78", "78 - Yvelines");
        map.put("79", "79 - Deux-Sèvres");
        map.put("80", "80 - Somme");
        map.put("81", "81 - Tarn");
        map.put("82", "82 - Tarn-et-Garonne");
        map.put("83", "83 - Var");
        map.put("84", "84 - Vaucluse");
        map.put("85", "85 - Vendée");
        map.put("86", "86 - Vienne");
        map.put("87", "87 - Haute-Vienne");
        map.put("88", "88 - Vosges");
        map.put("89", "89 - Yonne");
        map.put("90", "90 - Territoire de Belfort");
        map.put("91", "91 - Essonne");
        map.put("92", "92 - Hauts-de-Seine");
        map.put("93", "93 - Seine-St-Denis");
        map.put("94", "94 - Val-de-Marne");
        map.put("95", "95 - Val-D'Oise");
        return map;
    }
}
